In [1]:
# Reload modules automatically
# https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html
%load_ext autoreload
%autoreload 2

In [2]:
from utils import ExperimentManager

In [ ]:
gcn_exp = dict(
    label = "GCN",
    collection = "l_sbm_cert_gcn",
    start_id = 1,
    end_id = 490,
    n_seeds = 5,
)
Ks = [1.5]
delta_l = [0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1]
n_adv_l = [1, 2, 6, 12, 24, 60, 120]

experiments = [gcn_exp]
experiment_manager = ExperimentManager(experiments)

In [5]:
experiment_manager.plot_cert_acc_delta(K=1.5, C_l=[0.01], delta_l=delta_l, 
                                       n_adv_l=n_adv_l)

---- Details of best experiment ----
ID: 331 ValAcc: 64.22 +- 6.62 TrnAcc: 69.73 +- 5.72 TestAcc: 61.38 +- 7.35
------------------------------------

               ValAcc            TrnAcc  regularizer
331  0.6422 +- 0.0662  0.6973 +- 0.0572       0.1000
291  0.6383 +- 0.0687  0.6853 +- 0.0583       0.0010
301  0.6355 +- 0.0646  0.6823 +- 0.0574       0.0050
321  0.6345 +- 0.0666  0.6840 +- 0.0555       0.0500
341  0.6165 +- 0.1132  0.6605 +- 0.1170       0.5000
351  0.6160 +- 0.1089  0.6517 +- 0.1178       1.0000
281  0.6160 +- 0.0430  0.6590 +- 0.0458       0.0001
311  0.6097 +- 0.0671  0.6668 +- 0.0696       0.0100
361  0.5125 +- 0.1148  0.5467 +- 0.1619       2.0000
371  0.3995 +- 0.1034  0.4117 +- 0.1380       5.0000
381  0.3052 +- 0.0989  0.2990 +- 0.1238      10.0000
391  0.2515 +- 0.0598  0.2220 +- 0.0745      50.0000
401  0.2333 +- 0.0546  0.2210 +- 0.0947     100.0000
411  0.2037 +- 0.0573  0.1815 +- 0.0730    1000.0000

In [4]:
start_id = 1
end_id = 560
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "pubmed"
collection= "ntk_gcn_hyperparam_pubmed_wikics" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 111 ValAcc: 79.92 +- 4.53 TrnAcc: 98.08 +- 1.12 TestAcc: 78.60 +- 2.07
------------------------------------

               ValAcc            TrnAcc  regularizer
111  0.7992 +- 0.0453  0.9808 +- 0.0112      50.0000
121  0.7967 +- 0.0379  0.9867 +- 0.0067     100.0000
91   0.7933 +- 0.0309  0.8892 +- 0.0321       5.0000
131  0.7925 +- 0.0342  0.9858 +- 0.0118    1000.0000
81   0.7892 +- 0.0312  0.8858 +- 0.0310       2.0000
101  0.7867 +- 0.0334  0.9175 +- 0.0206      10.0000
61   0.7867 +- 0.0342  0.8833 +- 0.0325       0.5000
51   0.7842 +- 0.0362  0.8775 +- 0.0344       0.1000
41   0.7833 +- 0.0369  0.8792 +- 0.0342       0.0500
71   0.7833 +- 0.0354  0.8775 +- 0.0342       1.0000
21   0.7800 +- 0.0314  0.8883 +- 0.0299       0.0050
31   0.7767 +- 0.0429  0.8825 +- 0.0330       0.0100
1    0.7533 +- 0.0500  0.8775 +- 0.0427       0.0001
11   0.7483 +- 0.0467  0.8642 +- 0.0396       0.0010

In [7]:
start_id = 1
end_id = 560
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "krr"
dataset = "pubmed"
collection= "ntk_gcn_hyperparam_pubmed_wikics" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 181 ValAcc: 80.92 +- 3.95 TrnAcc: 97.50 +- 0.91 TestAcc: 78.70 +- 2.13
------------------------------------

               ValAcc            TrnAcc  regularizer
181  0.8092 +- 0.0395  0.9750 +- 0.0091       0.0500
171  0.8067 +- 0.0399  0.9833 +- 0.0083       0.0100
211  0.8000 +- 0.0298  0.8942 +- 0.0239       1.0000
191  0.7992 +- 0.0404  0.9583 +- 0.0167       0.1000
161  0.7933 +- 0.0474  0.9825 +- 0.0095       0.0050
141  0.7917 +- 0.0443  0.9817 +- 0.0138       0.0001
201  0.7900 +- 0.0276  0.8975 +- 0.0256       0.5000
151  0.7875 +- 0.0443  0.9867 +- 0.0100       0.0010
221  0.7867 +- 0.0403  0.8867 +- 0.0245       2.0000
231  0.7625 +- 0.0282  0.8658 +- 0.0280       5.0000
241  0.7333 +- 0.0266  0.8467 +- 0.0323      10.0000
251  0.7008 +- 0.0399  0.8217 +- 0.0444      50.0000
261  0.6725 +- 0.0289  0.7958 +- 0.0424     100.0000
271  0.6675 +- 0.0287  0.7883 +- 0.0400    1000.0000

In [11]:
start_id = 1
end_id = 280
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora"
collection= "ntk_gcn_hyperparam" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 51 ValAcc: 81.50 +- 2.81 TrnAcc: 94.93 +- 0.98 TestAcc: 82.38 +- 2.33
------------------------------------

               ValAcc            TrnAcc  regularizer
51   0.8150 +- 0.0281  0.9493 +- 0.0098       0.1000
31   0.8104 +- 0.0270  0.9329 +- 0.0108       0.0100
41   0.8061 +- 0.0325  0.9336 +- 0.0089       0.0500
21   0.8057 +- 0.0360  0.9321 +- 0.0172       0.0050
61   0.7993 +- 0.0302  0.9761 +- 0.0104       0.5000
1    0.7989 +- 0.0248  0.9307 +- 0.0120       0.0001
11   0.7971 +- 0.0307  0.9311 +- 0.0161       0.0010
71   0.7729 +- 0.0332  0.9814 +- 0.0080       1.0000
91   0.7700 +- 0.0340  0.9829 +- 0.0109       5.0000
81   0.7646 +- 0.0376  0.9789 +- 0.0126       2.0000
101  0.7579 +- 0.0458  0.9689 +- 0.0388      10.0000
111  0.7571 +- 0.0462  0.9668 +- 0.0396      50.0000
131  0.7511 +- 0.0492  0.9650 +- 0.0390    1000.0000
121  0.7446 +- 0.0313  0.9725 +- 0.0185     100.0000

In [8]:
start_id = 1
end_id = 280
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "krr"
dataset = "cora"
collection= "ntk_gcn_hyperparam" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 231 ValAcc: 82.00 +- 2.25 TrnAcc: 97.54 +- 1.23 TestAcc: 82.05 +- 2.65
------------------------------------

               ValAcc            TrnAcc  regularizer
231  0.8200 +- 0.0225  0.9754 +- 0.0123       5.0000
241  0.8154 +- 0.0203  0.9600 +- 0.0109      10.0000
251  0.8150 +- 0.0273  0.9268 +- 0.0097      50.0000
261  0.8150 +- 0.0291  0.9168 +- 0.0095     100.0000
221  0.8018 +- 0.0339  0.9843 +- 0.0068       2.0000
211  0.7907 +- 0.0378  0.9871 +- 0.0058       1.0000
271  0.7893 +- 0.0291  0.8846 +- 0.0160    1000.0000
201  0.7761 +- 0.0491  0.9821 +- 0.0111       0.5000
181  0.7443 +- 0.0494  0.9425 +- 0.0506       0.0500
191  0.7439 +- 0.0501  0.9532 +- 0.0396       0.1000
151  0.7175 +- 0.0542  0.9011 +- 0.0861       0.0010
141  0.7157 +- 0.0548  0.9000 +- 0.0869       0.0001
161  0.7096 +- 0.0587  0.9039 +- 0.0808       0.0050
171  0.6914 +- 0.1304  0.8557 +- 0.1972       0.0100

In [9]:
start_id = 1
end_id = 840
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "krr"
dataset = "cora_ml"
collection= "ntk_gcn_hyperparam" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 531 ValAcc: 83.82 +- 2.01 TrnAcc: 93.29 +- 1.63 TestAcc: 83.20 +- 1.84
------------------------------------

               ValAcc            TrnAcc  regularizer
531  0.8382 +- 0.0201  0.9329 +- 0.0163      50.0000
541  0.8329 +- 0.0214  0.9157 +- 0.0177     100.0000
551  0.8307 +- 0.0121  0.8975 +- 0.0161    1000.0000
521  0.8304 +- 0.0196  0.9654 +- 0.0105      10.0000
511  0.8271 +- 0.0208  0.9811 +- 0.0101       5.0000
501  0.8154 +- 0.0217  0.9829 +- 0.0113       2.0000
491  0.8064 +- 0.0248  0.9804 +- 0.0135       1.0000
481  0.7793 +- 0.0355  0.9771 +- 0.0221       0.5000
471  0.7411 +- 0.0728  0.9221 +- 0.0996       0.1000
421  0.7346 +- 0.0772  0.9336 +- 0.0877       0.0001
461  0.7250 +- 0.0792  0.8950 +- 0.1397       0.0500
431  0.7150 +- 0.0923  0.8486 +- 0.2067       0.0010
441  0.7136 +- 0.0939  0.8729 +- 0.2015       0.0050
451  0.7100 +- 0.0910  0.8629 +- 0.1939       0.0100

In [6]:
start_id = 1
end_id = 840
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml"
collection= "ntk_gcn_hyperparam" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 321 ValAcc: 83.11 +- 2.61 TrnAcc: 93.61 +- 1.58 TestAcc: 82.78 +- 2.12
------------------------------------

               ValAcc            TrnAcc  regularizer
321  0.8311 +- 0.0261  0.9361 +- 0.0158       0.0500
331  0.8271 +- 0.0272  0.9571 +- 0.0144       0.1000
281  0.8246 +- 0.0250  0.9175 +- 0.0203       0.0001
301  0.8225 +- 0.0262  0.9186 +- 0.0203       0.0050
311  0.8221 +- 0.0257  0.9182 +- 0.0205       0.0100
291  0.8168 +- 0.0252  0.9175 +- 0.0159       0.0010
341  0.8075 +- 0.0240  0.9789 +- 0.0094       0.5000
351  0.8054 +- 0.0255  0.9818 +- 0.0137       1.0000
361  0.7918 +- 0.0331  0.9793 +- 0.0236       2.0000
391  0.7718 +- 0.0531  0.9843 +- 0.0113      50.0000
371  0.7657 +- 0.0696  0.9404 +- 0.1214       5.0000
381  0.7625 +- 0.0740  0.9389 +- 0.1257      10.0000
411  0.7614 +- 0.0830  0.9414 +- 0.1265    1000.0000
401  0.7482 +- 0.0744  0.9389 +- 0.1257     100.0000

In [10]:
start_id = 1
end_id = 840
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "krr"
dataset = "citeseer"
collection= "ntk_gcn_hyperparam" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 811 ValAcc: 69.21 +- 2.14 TrnAcc: 88.25 +- 2.29 TestAcc: 74.44 +- 2.64
------------------------------------

               ValAcc            TrnAcc  regularizer
811  0.6921 +- 0.0214  0.8825 +- 0.0229      50.0000
801  0.6783 +- 0.0304  0.9458 +- 0.0136      10.0000
821  0.6779 +- 0.0294  0.8521 +- 0.0218     100.0000
831  0.6758 +- 0.0220  0.8125 +- 0.0185    1000.0000
791  0.6708 +- 0.0347  0.9654 +- 0.0072       5.0000
781  0.6521 +- 0.0325  0.9704 +- 0.0119       2.0000
771  0.6367 +- 0.0362  0.9738 +- 0.0105       1.0000
761  0.6283 +- 0.0350  0.9696 +- 0.0141       0.5000
751  0.6067 +- 0.0601  0.9613 +- 0.0459       0.1000
741  0.5938 +- 0.0606  0.9271 +- 0.0985       0.0500
731  0.5842 +- 0.0732  0.9088 +- 0.1225       0.0100
701  0.5787 +- 0.0752  0.9050 +- 0.1280       0.0001
721  0.5708 +- 0.0874  0.8767 +- 0.2144       0.0050
711  0.5667 +- 0.1005  0.8375 +- 0.2539       0.0010

In [12]:
start_id = 1
end_id = 840
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "citeseer"
collection= "ntk_gcn_hyperparam" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 601 ValAcc: 68.42 +- 2.78 TrnAcc: 89.33 +- 1.75 TestAcc: 73.36 +- 2.39
------------------------------------

               ValAcc            TrnAcc  regularizer
601  0.6842 +- 0.0278  0.8933 +- 0.0175       0.0500
591  0.6825 +- 0.0277  0.8771 +- 0.0249       0.0100
571  0.6775 +- 0.0270  0.8758 +- 0.0203       0.0010
611  0.6771 +- 0.0295  0.9213 +- 0.0177       0.1000
561  0.6762 +- 0.0281  0.8733 +- 0.0203       0.0001
581  0.6754 +- 0.0291  0.8754 +- 0.0204       0.0050
621  0.6392 +- 0.0338  0.9675 +- 0.0105       0.5000
631  0.6250 +- 0.0334  0.9667 +- 0.0133       1.0000
661  0.6204 +- 0.0549  0.9558 +- 0.0677      10.0000
671  0.6104 +- 0.0467  0.9483 +- 0.0644      50.0000
651  0.6104 +- 0.0473  0.9496 +- 0.0593       5.0000
691  0.6104 +- 0.0467  0.9471 +- 0.0638    1000.0000
641  0.6100 +- 0.0406  0.9621 +- 0.0280       2.0000
681  0.6025 +- 0.0844  0.9096 +- 0.1992     100.0000

In [4]:
start_id = 1
end_id = 100
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "pubmed"
collection= "ntk_gcn_hyperparam_pubmed_wikics" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

              ValAcc            TrnAcc  regularizer
91  0.7933 +- 0.0309  0.8892 +- 0.0321       5.0000
81  0.7892 +- 0.0312  0.8858 +- 0.0310       2.0000
61  0.7867 +- 0.0342  0.8833 +- 0.0325       0.5000
51  0.7842 +- 0.0362  0.8775 +- 0.0344       0.1000
41  0.7833 +- 0.0369  0.8792 +- 0.0342       0.0500
71  0.7833 +- 0.0354  0.8775 +- 0.0342       1.0000
21  0.7800 +- 0.0314  0.8883 +- 0.0299       0.0050
31  0.7767 +- 0.0429  0.8825 +- 0.0330       0.0100
1   0.7533 +- 0.0500  0.8775 +- 0.0427       0.0001
11  0.7483 +- 0.0467  0.8642 +- 0.0396       0.0010