In [1]:
# Reload modules automatically
# https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html
%load_ext autoreload
%autoreload 2

In [2]:
import utils
import pandas as pd

In [12]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 71 ValAcc: 98.00 +- 2.45 TrnAcc: 100.00 +- 0.00 TestAcc: 97.00 +- 1.36
------------------------------------

               ValAcc            TrnAcc  regularizer
71   0.9800 +- 0.0245  1.0000 +- 0.0000       0.0750
81   0.9800 +- 0.0245  1.0000 +- 0.0000       0.1000
91   0.9800 +- 0.0245  1.0000 +- 0.0000       0.2500
101  0.9800 +- 0.0245  1.0000 +- 0.0000       0.5000
111  0.9800 +- 0.0245  1.0000 +- 0.0000       0.7500
121  0.9800 +- 0.0245  1.0000 +- 0.0000       1.0000
131  0.9800 +- 0.0245  1.0000 +- 0.0000       2.5000
141  0.9800 +- 0.0245  1.0000 +- 0.0000       5.0000
151  0.9800 +- 0.0245  1.0000 +- 0.0000       7.5000
161  0.9800 +- 0.0245  1.0000 +- 0.0000      10.0000
61   0.9650 +- 0.0391  1.0000 +- 0.0000       0.0500
51   0.8800 +- 0.1100  1.0000 +- 0.0000       0.0250
1    0.7500 +- 0.0837  0.9700 +- 0.0458       0.0010
11   0.7500 +- 0.0837  0.9700 +- 0.0458       0.0025
21   0.7500 +- 0.0837  0.9700 +- 0.0458       0.0050
31   0.7500 +- 0.0837  0.9700 +- 0.0458       0.0075
41   0.7500 +- 0.0837  0.9750 +- 0.0461       0.0100

In [11]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_sym" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 71 ValAcc: 96.00 +- 4.36 TrnAcc: 100.00 +- 0.00 TestAcc: 94.02 +- 3.82
------------------------------------

               ValAcc            TrnAcc  regularizer
71   0.9600 +- 0.0436  1.0000 +- 0.0000       0.0750
81   0.9550 +- 0.0522  1.0000 +- 0.0000       0.1000
61   0.9550 +- 0.0568  1.0000 +- 0.0000       0.0500
91   0.9250 +- 0.0750  1.0000 +- 0.0000       0.2500
101  0.9200 +- 0.0781  1.0000 +- 0.0000       0.5000
111  0.9200 +- 0.0781  1.0000 +- 0.0000       0.7500
121  0.9200 +- 0.0781  1.0000 +- 0.0000       1.0000
131  0.9200 +- 0.0781  1.0000 +- 0.0000       2.5000
141  0.9200 +- 0.0781  1.0000 +- 0.0000       5.0000
151  0.9200 +- 0.0781  1.0000 +- 0.0000       7.5000
161  0.9200 +- 0.0781  1.0000 +- 0.0000      10.0000
51   0.7750 +- 0.1346  1.0000 +- 0.0000       0.0250
1    0.6600 +- 0.1158  0.8300 +- 0.1833       0.0010
11   0.6600 +- 0.1158  0.8300 +- 0.1833       0.0025
21   0.6600 +- 0.1158  0.8300 +- 0.1833       0.0050
31   0.6600 +- 0.1158  0.8350 +- 0.1747       0.0075
41   0.6600 +- 0.1158  0.8450 +- 0.1604       0.0100

In [13]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_sgc" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 71 ValAcc: 97.50 +- 2.50 TrnAcc: 100.00 +- 0.00 TestAcc: 95.96 +- 1.53
------------------------------------

               ValAcc            TrnAcc  regularizer
71   0.9750 +- 0.0250  1.0000 +- 0.0000       0.0750
81   0.9750 +- 0.0250  1.0000 +- 0.0000       0.1000
61   0.9700 +- 0.0245  1.0000 +- 0.0000       0.0500
91   0.9700 +- 0.0245  1.0000 +- 0.0000       0.2500
101  0.9700 +- 0.0245  1.0000 +- 0.0000       0.5000
111  0.9700 +- 0.0245  1.0000 +- 0.0000       0.7500
121  0.9700 +- 0.0245  1.0000 +- 0.0000       1.0000
131  0.9700 +- 0.0245  1.0000 +- 0.0000       2.5000
141  0.9700 +- 0.0245  1.0000 +- 0.0000       5.0000
151  0.9700 +- 0.0245  1.0000 +- 0.0000       7.5000
161  0.9700 +- 0.0245  1.0000 +- 0.0000      10.0000
51   0.9650 +- 0.0502  1.0000 +- 0.0000       0.0250
41   0.9200 +- 0.0843  1.0000 +- 0.0000       0.0100
1    0.9150 +- 0.0867  1.0000 +- 0.0000       0.0010
11   0.9150 +- 0.0867  1.0000 +- 0.0000       0.0025
21   0.9150 +- 0.0867  1.0000 +- 0.0000       0.0050
31   0.9150 +- 0.0867  1.0000 +- 0.0000       0.0075

In [14]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_sgc_sym" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 61 ValAcc: 97.00 +- 3.32 TrnAcc: 100.00 +- 0.00 TestAcc: 95.51 +- 2.07
------------------------------------

               ValAcc            TrnAcc  regularizer
61   0.9700 +- 0.0332  1.0000 +- 0.0000       0.0500
71   0.9700 +- 0.0332  1.0000 +- 0.0000       0.0750
81   0.9700 +- 0.0332  1.0000 +- 0.0000       0.1000
91   0.9650 +- 0.0320  1.0000 +- 0.0000       0.2500
101  0.9650 +- 0.0320  1.0000 +- 0.0000       0.5000
111  0.9650 +- 0.0320  1.0000 +- 0.0000       0.7500
121  0.9650 +- 0.0320  1.0000 +- 0.0000       1.0000
131  0.9650 +- 0.0320  1.0000 +- 0.0000       2.5000
141  0.9650 +- 0.0320  1.0000 +- 0.0000       5.0000
151  0.9650 +- 0.0320  1.0000 +- 0.0000       7.5000
161  0.9650 +- 0.0320  1.0000 +- 0.0000      10.0000
51   0.9600 +- 0.0436  1.0000 +- 0.0000       0.0250
41   0.8700 +- 0.0954  0.9950 +- 0.0150       0.0100
1    0.8550 +- 0.1083  0.9900 +- 0.0300       0.0010
11   0.8550 +- 0.1083  0.9900 +- 0.0300       0.0025
21   0.8550 +- 0.1083  0.9900 +- 0.0300       0.0050
31   0.8550 +- 0.1083  0.9900 +- 0.0300       0.0075

In [17]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_mlp" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 51 ValAcc: 79.00 +- 12.21 TrnAcc: 100.00 +- 0.00 TestAcc: 83.26 +- 2.72
------------------------------------

               ValAcc            TrnAcc  regularizer
51   0.7900 +- 0.1221  1.0000 +- 0.0000       0.0250
61   0.7750 +- 0.1230  1.0000 +- 0.0000       0.0500
71   0.7700 +- 0.1229  1.0000 +- 0.0000       0.0750
81   0.7600 +- 0.1221  1.0000 +- 0.0000       0.1000
91   0.7600 +- 0.1221  1.0000 +- 0.0000       0.2500
101  0.7600 +- 0.1221  1.0000 +- 0.0000       0.5000
111  0.7600 +- 0.1221  1.0000 +- 0.0000       0.7500
121  0.7600 +- 0.1221  1.0000 +- 0.0000       1.0000
131  0.7600 +- 0.1221  1.0000 +- 0.0000       2.5000
141  0.7600 +- 0.1221  1.0000 +- 0.0000       5.0000
151  0.7600 +- 0.1221  1.0000 +- 0.0000       7.5000
161  0.7600 +- 0.1221  1.0000 +- 0.0000      10.0000
41   0.6500 +- 0.0548  1.0000 +- 0.0000       0.0100
31   0.5300 +- 0.0781  1.0000 +- 0.0000       0.0075
21   0.5150 +- 0.0743  1.0000 +- 0.0000       0.0050
1    0.5050 +- 0.0687  1.0000 +- 0.0000       0.0010
11   0.5050 +- 0.0687  1.0000 +- 0.0000       0.0025

In [18]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gin" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 51 ValAcc: 93.50 +- 7.43 TrnAcc: 100.00 +- 0.00 TestAcc: 93.65 +- 2.38
------------------------------------

               ValAcc            TrnAcc  regularizer
51   0.9350 +- 0.0743  1.0000 +- 0.0000       0.0250
61   0.9350 +- 0.0743  1.0000 +- 0.0000       0.0500
71   0.9350 +- 0.0743  1.0000 +- 0.0000       0.0750
81   0.9350 +- 0.0743  1.0000 +- 0.0000       0.1000
91   0.9350 +- 0.0743  1.0000 +- 0.0000       0.2500
101  0.9350 +- 0.0743  1.0000 +- 0.0000       0.5000
111  0.9350 +- 0.0743  1.0000 +- 0.0000       0.7500
121  0.9350 +- 0.0743  1.0000 +- 0.0000       1.0000
131  0.9350 +- 0.0743  1.0000 +- 0.0000       2.5000
141  0.9350 +- 0.0743  1.0000 +- 0.0000       5.0000
151  0.9350 +- 0.0743  1.0000 +- 0.0000       7.5000
161  0.9350 +- 0.0743  1.0000 +- 0.0000      10.0000
31   0.9300 +- 0.0900  1.0000 +- 0.0000       0.0075
41   0.9300 +- 0.0927  1.0000 +- 0.0000       0.0100
21   0.9250 +- 0.0901  0.9950 +- 0.0150       0.0050
11   0.9200 +- 0.1030  0.9950 +- 0.0150       0.0025
1    0.7800 +- 0.1269  1.0000 +- 0.0000       0.0010

In [19]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_graphsage" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 31 ValAcc: 95.50 +- 3.50 TrnAcc: 100.00 +- 0.00 TestAcc: 95.15 +- 1.86
------------------------------------

               ValAcc            TrnAcc  regularizer
31   0.9550 +- 0.0350  1.0000 +- 0.0000       0.0075
41   0.9550 +- 0.0350  1.0000 +- 0.0000       0.0100
51   0.9550 +- 0.0350  1.0000 +- 0.0000       0.0250
61   0.9550 +- 0.0350  1.0000 +- 0.0000       0.0500
71   0.9550 +- 0.0350  1.0000 +- 0.0000       0.0750
81   0.9550 +- 0.0350  1.0000 +- 0.0000       0.1000
91   0.9550 +- 0.0350  1.0000 +- 0.0000       0.2500
101  0.9550 +- 0.0350  1.0000 +- 0.0000       0.5000
111  0.9550 +- 0.0350  1.0000 +- 0.0000       0.7500
121  0.9550 +- 0.0350  1.0000 +- 0.0000       1.0000
131  0.9550 +- 0.0350  1.0000 +- 0.0000       2.5000
141  0.9550 +- 0.0350  1.0000 +- 0.0000       5.0000
151  0.9550 +- 0.0350  1.0000 +- 0.0000       7.5000
161  0.9550 +- 0.0350  1.0000 +- 0.0000      10.0000
21   0.9500 +- 0.0387  1.0000 +- 0.0000       0.0050
11   0.9150 +- 0.0550  1.0000 +- 0.0000       0.0025
1    0.7200 +- 0.1005  1.0000 +- 0.0000       0.0010

In [20]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skippc" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 71 ValAcc: 96.50 +- 3.91 TrnAcc: 100.00 +- 0.00 TestAcc: 96.12 +- 1.56
------------------------------------

               ValAcc            TrnAcc  regularizer
71   0.9650 +- 0.0391  1.0000 +- 0.0000       0.0750
81   0.9650 +- 0.0391  1.0000 +- 0.0000       0.1000
91   0.9650 +- 0.0391  1.0000 +- 0.0000       0.2500
101  0.9650 +- 0.0391  1.0000 +- 0.0000       0.5000
111  0.9650 +- 0.0391  1.0000 +- 0.0000       0.7500
121  0.9650 +- 0.0391  1.0000 +- 0.0000       1.0000
131  0.9650 +- 0.0391  1.0000 +- 0.0000       2.5000
141  0.9650 +- 0.0391  1.0000 +- 0.0000       5.0000
151  0.9650 +- 0.0391  1.0000 +- 0.0000       7.5000
161  0.9650 +- 0.0391  1.0000 +- 0.0000      10.0000
51   0.9600 +- 0.0374  1.0000 +- 0.0000       0.0250
61   0.9600 +- 0.0374  1.0000 +- 0.0000       0.0500
41   0.8400 +- 0.0995  1.0000 +- 0.0000       0.0100
31   0.8050 +- 0.0986  1.0000 +- 0.0000       0.0075
1    0.7950 +- 0.1036  1.0000 +- 0.0000       0.0010
11   0.7950 +- 0.1036  1.0000 +- 0.0000       0.0025
21   0.7950 +- 0.1036  1.0000 +- 0.0000       0.0050

In [22]:
start_id = 1
end_id = 680
n_seeds = 10
hyperparams = ["regularizer", "skip_alpha"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skipalpha" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 321 ValAcc: 98.00 +- 2.45 TrnAcc: 100.00 +- 0.00 TestAcc: 96.74 +- 1.45
------------------------------------

               ValAcc            TrnAcc  regularizer  skip_alpha
321  0.9800 +- 0.0245  1.0000 +- 0.0000       0.1000         0.1
361  0.9800 +- 0.0245  1.0000 +- 0.0000       0.2500         0.1
401  0.9800 +- 0.0245  1.0000 +- 0.0000       0.5000         0.1
441  0.9800 +- 0.0245  1.0000 +- 0.0000       0.7500         0.1
481  0.9800 +- 0.0245  1.0000 +- 0.0000       1.0000         0.1
..                ...               ...          ...         ...
1    0.7550 +- 0.0850  0.9900 +- 0.0200       0.0010         0.1
41   0.7550 +- 0.0850  0.9900 +- 0.0200       0.0025         0.1
81   0.7550 +- 0.0850  0.9900 +- 0.0200       0.0050         0.1
121  0.7550 +- 0.0850  0.9900 +- 0.0200       0.0075         0.1
161  0.7550 +- 0.0850  0.9900 +- 0.0200       0.0100         0.1

[68 rows x 4 columns]

In [27]:
start_id = 1
end_id = 850
n_seeds = 10
hyperparams = ["regularizer", "alpha"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_appnp" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 101 ValAcc: 99.50 +- 1.50 TrnAcc: 100.00 +- 0.00 TestAcc: 96.44 +- 1.08
------------------------------------

               ValAcc            TrnAcc  regularizer  alpha
101  0.9950 +- 0.0150  1.0000 +- 0.0000       0.5000    0.0
111  0.9950 +- 0.0150  1.0000 +- 0.0000       0.7500    0.0
91   0.9900 +- 0.0200  1.0000 +- 0.0000       0.2500    0.0
121  0.9900 +- 0.0200  1.0000 +- 0.0000       1.0000    0.0
81   0.9800 +- 0.0245  1.0000 +- 0.0000       0.1000    0.0
..                ...               ...          ...    ...
511  0.5400 +- 0.0663  0.8800 +- 0.1661       0.0010    0.3
521  0.5400 +- 0.0663  0.8800 +- 0.1661       0.0025    0.3
531  0.5400 +- 0.0663  0.8800 +- 0.1661       0.0050    0.3
541  0.5400 +- 0.0663  0.8850 +- 0.1550       0.0075    0.3
551  0.5400 +- 0.0663  0.9100 +- 0.1091       0.0100    0.3

[85 rows x 4 columns]