In [2]:
# Reload modules automatically
# https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html
%load_ext autoreload
%autoreload 2

In [3]:
import utils
import pandas as pd

In [30]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skippc_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 61 ValAcc: 98.00 +- 2.45 TrnAcc: 100.00 +- 0.00 TestAcc: 96.79 +- 1.41
------------------------------------

               ValAcc            TrnAcc  regularizer
61   0.9800 +- 0.0245  1.0000 +- 0.0000       0.0500
71   0.9800 +- 0.0245  1.0000 +- 0.0000       0.0750
81   0.9800 +- 0.0245  1.0000 +- 0.0000       0.1000
91   0.9800 +- 0.0245  1.0000 +- 0.0000       0.2500
101  0.9800 +- 0.0245  1.0000 +- 0.0000       0.5000
111  0.9800 +- 0.0245  1.0000 +- 0.0000       0.7500
121  0.9800 +- 0.0245  1.0000 +- 0.0000       1.0000
131  0.9800 +- 0.0245  1.0000 +- 0.0000       2.5000
141  0.9800 +- 0.0245  1.0000 +- 0.0000       5.0000
151  0.9800 +- 0.0245  1.0000 +- 0.0000       7.5000
161  0.9800 +- 0.0245  1.0000 +- 0.0000      10.0000
51   0.9750 +- 0.0250  1.0000 +- 0.0000       0.0250
41   0.9250 +- 0.0750  1.0000 +- 0.0000       0.0100
31   0.8700 +- 0.0980  1.0000 +- 0.0000       0.0075
21   0.7650 +- 0.0896  0.9900 +- 0.0300       0.0050
1    0.7450 +- 0.0789  0.9750 +- 0.0461       0.0010
11   0.7450 +- 0.0789  0.9750 +- 0.0461       0.0025

In [31]:
start_id = 171
end_id = 340
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skippc_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 211 ValAcc: 99.00 +- 2.00 TrnAcc: 100.00 +- 0.00 TestAcc: 96.83 +- 0.98
------------------------------------

               ValAcc            TrnAcc  regularizer
211  0.9900 +- 0.0200  1.0000 +- 0.0000       0.0100
221  0.9850 +- 0.0229  1.0000 +- 0.0000       0.0250
231  0.9850 +- 0.0229  1.0000 +- 0.0000       0.0500
241  0.9850 +- 0.0229  1.0000 +- 0.0000       0.0750
251  0.9850 +- 0.0229  1.0000 +- 0.0000       0.1000
261  0.9850 +- 0.0229  1.0000 +- 0.0000       0.2500
271  0.9850 +- 0.0229  1.0000 +- 0.0000       0.5000
281  0.9850 +- 0.0229  1.0000 +- 0.0000       0.7500
291  0.9850 +- 0.0229  1.0000 +- 0.0000       1.0000
301  0.9850 +- 0.0229  1.0000 +- 0.0000       2.5000
311  0.9850 +- 0.0229  1.0000 +- 0.0000       5.0000
321  0.9850 +- 0.0229  1.0000 +- 0.0000       7.5000
331  0.9850 +- 0.0229  1.0000 +- 0.0000      10.0000
201  0.9650 +- 0.0391  1.0000 +- 0.0000       0.0075
191  0.9350 +- 0.0743  1.0000 +- 0.0000       0.0050
181  0.7400 +- 0.0539  0.9800 +- 0.0458       0.0025
171  0.7100 +- 0.0539  0.8950 +- 0.1234       0.0010

In [16]:
start_id = 301
end_id = 450
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skippc_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 301 ValAcc: 98.50 +- 2.29 TrnAcc: 100.00 +- 0.00 TestAcc: 96.65 +- 1.02
------------------------------------

               ValAcc            TrnAcc  regularizer
301  0.9850 +- 0.0229  1.0000 +- 0.0000       2.5000
311  0.9850 +- 0.0229  1.0000 +- 0.0000       5.0000
321  0.9850 +- 0.0229  1.0000 +- 0.0000       7.5000
331  0.9850 +- 0.0229  1.0000 +- 0.0000      10.0000
361  0.9650 +- 0.0320  0.9950 +- 0.0150       0.0050
371  0.9650 +- 0.0320  1.0000 +- 0.0000       0.0075
381  0.9650 +- 0.0320  1.0000 +- 0.0000       0.0100
391  0.9650 +- 0.0320  1.0000 +- 0.0000       0.0250
401  0.9650 +- 0.0320  1.0000 +- 0.0000       0.0500
411  0.9650 +- 0.0320  1.0000 +- 0.0000       0.0750
421  0.9650 +- 0.0320  1.0000 +- 0.0000       0.1000
431  0.9650 +- 0.0320  1.0000 +- 0.0000       0.2500
441  0.9650 +- 0.0320  1.0000 +- 0.0000       0.5000
351  0.9050 +- 0.0415  0.9950 +- 0.0150       0.0025
341  0.7550 +- 0.0789  0.9750 +- 0.0335       0.0010

In [17]:
start_id = 451
end_id = 600
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skippc_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 451 ValAcc: 96.50 +- 3.20 TrnAcc: 100.00 +- 0.00 TestAcc: 96.16 +- 1.09
------------------------------------

               ValAcc            TrnAcc  regularizer
451  0.9650 +- 0.0320  1.0000 +- 0.0000       0.7500
461  0.9650 +- 0.0320  1.0000 +- 0.0000       1.0000
471  0.9650 +- 0.0320  1.0000 +- 0.0000       2.5000
481  0.9650 +- 0.0320  1.0000 +- 0.0000       5.0000
491  0.9650 +- 0.0320  1.0000 +- 0.0000       7.5000
501  0.9650 +- 0.0320  1.0000 +- 0.0000      10.0000
521  0.9550 +- 0.0350  0.9900 +- 0.0200       0.0025
531  0.9550 +- 0.0350  1.0000 +- 0.0000       0.0050
541  0.9550 +- 0.0350  1.0000 +- 0.0000       0.0075
551  0.9550 +- 0.0350  1.0000 +- 0.0000       0.0100
561  0.9550 +- 0.0350  1.0000 +- 0.0000       0.0250
571  0.9550 +- 0.0350  1.0000 +- 0.0000       0.0500
581  0.9550 +- 0.0350  1.0000 +- 0.0000       0.0750
591  0.9550 +- 0.0350  1.0000 +- 0.0000       0.1000
511  0.9200 +- 0.0510  0.9900 +- 0.0200       0.0010

# SGC

In [9]:
start_id = 1
end_id = 150
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_sgc_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 71 ValAcc: 97.50 +- 2.50 TrnAcc: 100.00 +- 0.00 TestAcc: 95.96 +- 1.53
------------------------------------

               ValAcc            TrnAcc  regularizer
71   0.9750 +- 0.0250  1.0000 +- 0.0000       0.0750
81   0.9750 +- 0.0250  1.0000 +- 0.0000       0.1000
61   0.9700 +- 0.0245  1.0000 +- 0.0000       0.0500
91   0.9700 +- 0.0245  1.0000 +- 0.0000       0.2500
101  0.9700 +- 0.0245  1.0000 +- 0.0000       0.5000
111  0.9700 +- 0.0245  1.0000 +- 0.0000       0.7500
121  0.9700 +- 0.0245  1.0000 +- 0.0000       1.0000
131  0.9700 +- 0.0245  1.0000 +- 0.0000       2.5000
141  0.9700 +- 0.0245  1.0000 +- 0.0000       5.0000
51   0.9650 +- 0.0502  1.0000 +- 0.0000       0.0250
41   0.9200 +- 0.0843  1.0000 +- 0.0000       0.0100
1    0.9150 +- 0.0867  1.0000 +- 0.0000       0.0010
11   0.9150 +- 0.0867  1.0000 +- 0.0000       0.0025
21   0.9150 +- 0.0867  1.0000 +- 0.0000       0.0050
31   0.9150 +- 0.0867  1.0000 +- 0.0000       0.0075

In [10]:
start_id = 151
end_id = 300
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_sgc_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 241 ValAcc: 97.50 +- 2.50 TrnAcc: 100.00 +- 0.00 TestAcc: 95.96 +- 1.53
------------------------------------

               ValAcc            TrnAcc  regularizer
241  0.9750 +- 0.0250  1.0000 +- 0.0000       0.0750
251  0.9750 +- 0.0250  1.0000 +- 0.0000       0.1000
151  0.9700 +- 0.0245  1.0000 +- 0.0000       7.5000
161  0.9700 +- 0.0245  1.0000 +- 0.0000      10.0000
231  0.9700 +- 0.0245  1.0000 +- 0.0000       0.0500
261  0.9700 +- 0.0245  1.0000 +- 0.0000       0.2500
271  0.9700 +- 0.0245  1.0000 +- 0.0000       0.5000
281  0.9700 +- 0.0245  1.0000 +- 0.0000       0.7500
291  0.9700 +- 0.0245  1.0000 +- 0.0000       1.0000
221  0.9650 +- 0.0502  1.0000 +- 0.0000       0.0250
211  0.9200 +- 0.0843  1.0000 +- 0.0000       0.0100
171  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0010
181  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0025
191  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0050
201  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0075

In [12]:
start_id = 301
end_id = 450
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_sgc_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 411 ValAcc: 97.50 +- 2.50 TrnAcc: 100.00 +- 0.00 TestAcc: 95.96 +- 1.53
------------------------------------

               ValAcc            TrnAcc  regularizer
411  0.9750 +- 0.0250  1.0000 +- 0.0000       0.0750
421  0.9750 +- 0.0250  1.0000 +- 0.0000       0.1000
301  0.9700 +- 0.0245  1.0000 +- 0.0000       2.5000
311  0.9700 +- 0.0245  1.0000 +- 0.0000       5.0000
321  0.9700 +- 0.0245  1.0000 +- 0.0000       7.5000
331  0.9700 +- 0.0245  1.0000 +- 0.0000      10.0000
401  0.9700 +- 0.0245  1.0000 +- 0.0000       0.0500
431  0.9700 +- 0.0245  1.0000 +- 0.0000       0.2500
441  0.9700 +- 0.0245  1.0000 +- 0.0000       0.5000
391  0.9650 +- 0.0502  1.0000 +- 0.0000       0.0250
381  0.9200 +- 0.0843  1.0000 +- 0.0000       0.0100
341  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0010
351  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0025
361  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0050
371  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0075

In [13]:
start_id = 451
end_id = 600
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_sgc_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 581 ValAcc: 97.50 +- 2.50 TrnAcc: 100.00 +- 0.00 TestAcc: 95.96 +- 1.53
------------------------------------

               ValAcc            TrnAcc  regularizer
581  0.9750 +- 0.0250  1.0000 +- 0.0000       0.0750
591  0.9750 +- 0.0250  1.0000 +- 0.0000       0.1000
451  0.9700 +- 0.0245  1.0000 +- 0.0000       0.7500
461  0.9700 +- 0.0245  1.0000 +- 0.0000       1.0000
471  0.9700 +- 0.0245  1.0000 +- 0.0000       2.5000
481  0.9700 +- 0.0245  1.0000 +- 0.0000       5.0000
491  0.9700 +- 0.0245  1.0000 +- 0.0000       7.5000
501  0.9700 +- 0.0245  1.0000 +- 0.0000      10.0000
571  0.9700 +- 0.0245  1.0000 +- 0.0000       0.0500
561  0.9650 +- 0.0502  1.0000 +- 0.0000       0.0250
551  0.9200 +- 0.0843  1.0000 +- 0.0000       0.0100
511  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0010
521  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0025
531  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0050
541  0.9150 +- 0.0867  1.0000 +- 0.0000       0.0075

# GCN

In [28]:
start_id = 1
end_id = 170
n_seeds = 10
hyperparams = ["regularizer", "depth"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 61 ValAcc: 97.50 +- 3.35 TrnAcc: 100.00 +- 0.00 TestAcc: 96.57 +- 1.18
------------------------------------

               ValAcc            TrnAcc  regularizer  depth
61   0.9750 +- 0.0335  1.0000 +- 0.0000       0.0500      2
71   0.9750 +- 0.0335  1.0000 +- 0.0000       0.0750      2
81   0.9750 +- 0.0335  1.0000 +- 0.0000       0.1000      2
91   0.9750 +- 0.0335  1.0000 +- 0.0000       0.2500      2
101  0.9750 +- 0.0335  1.0000 +- 0.0000       0.5000      2
111  0.9750 +- 0.0335  1.0000 +- 0.0000       0.7500      2
121  0.9750 +- 0.0335  1.0000 +- 0.0000       1.0000      2
131  0.9750 +- 0.0335  1.0000 +- 0.0000       2.5000      2
141  0.9750 +- 0.0335  1.0000 +- 0.0000       5.0000      2
151  0.9750 +- 0.0335  1.0000 +- 0.0000       7.5000      2
161  0.9750 +- 0.0335  1.0000 +- 0.0000      10.0000      2
51   0.9300 +- 0.0678  0.9950 +- 0.0150       0.0250      2
41   0.6900 +- 0.0583  0.9400 +- 0.0800       0.0100      2
31   0.6800 +- 0.0557  0.8950 +- 0.1234       0.0075      2
1    0.6750 +- 0.0559  0.8600 +- 0.1546       0.0010      2
11   0.6750 +- 0.0559  0.8600 +- 0.1546       0.0025      2
21   0.6750 +- 0.0559  0.8600 +- 0.1546       0.0050      2

In [29]:
start_id = 171
end_id = 340
n_seeds = 10
hyperparams = ["regularizer", "depth"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 251 ValAcc: 95.00 +- 3.87 TrnAcc: 100.00 +- 0.00 TestAcc: 93.27 +- 2.77
------------------------------------

               ValAcc            TrnAcc  regularizer  depth
251  0.9500 +- 0.0387  1.0000 +- 0.0000       0.1000      4
231  0.9450 +- 0.0350  0.9900 +- 0.0200       0.0500      4
241  0.9450 +- 0.0350  1.0000 +- 0.0000       0.0750      4
261  0.9400 +- 0.0374  1.0000 +- 0.0000       0.2500      4
271  0.9400 +- 0.0374  1.0000 +- 0.0000       0.5000      4
281  0.9400 +- 0.0374  1.0000 +- 0.0000       0.7500      4
291  0.9400 +- 0.0374  1.0000 +- 0.0000       1.0000      4
301  0.9400 +- 0.0374  1.0000 +- 0.0000       2.5000      4
311  0.9400 +- 0.0374  1.0000 +- 0.0000       5.0000      4
321  0.9400 +- 0.0374  1.0000 +- 0.0000       7.5000      4
331  0.9400 +- 0.0374  1.0000 +- 0.0000      10.0000      4
221  0.8950 +- 0.0568  0.9900 +- 0.0200       0.0250      4
211  0.8600 +- 0.0490  0.9550 +- 0.0472       0.0100      4
201  0.8050 +- 0.0610  0.9250 +- 0.0461       0.0075      4
191  0.7550 +- 0.0522  0.9050 +- 0.0472       0.0050      4
171  0.7400 +- 0.0539  0.8850 +- 0.0550       0.0010      4
181  0.7400 +- 0.0539  0.8850 +- 0.0550       0.0025      4

In [6]:
start_id = 301
end_id = 450
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 301 ValAcc: 94.00 +- 3.74 TrnAcc: 100.00 +- 0.00 TestAcc: 93.51 +- 2.61
------------------------------------

               ValAcc            TrnAcc  regularizer
301  0.9400 +- 0.0374  1.0000 +- 0.0000       2.5000
311  0.9400 +- 0.0374  1.0000 +- 0.0000       5.0000
321  0.9400 +- 0.0374  1.0000 +- 0.0000       7.5000
331  0.9400 +- 0.0374  1.0000 +- 0.0000      10.0000
431  0.9350 +- 0.0320  1.0000 +- 0.0000       0.2500
441  0.9350 +- 0.0320  1.0000 +- 0.0000       0.5000
421  0.9300 +- 0.0458  0.9950 +- 0.0150       0.1000
411  0.9200 +- 0.0557  0.9950 +- 0.0150       0.0750
401  0.9150 +- 0.0550  0.9850 +- 0.0229       0.0500
391  0.9100 +- 0.0490  0.9600 +- 0.0374       0.0250
341  0.9050 +- 0.0610  0.9300 +- 0.0640       0.0010
351  0.9050 +- 0.0610  0.9300 +- 0.0640       0.0025
381  0.9050 +- 0.0610  0.9350 +- 0.0550       0.0100
361  0.9000 +- 0.0632  0.9350 +- 0.0550       0.0050
371  0.8950 +- 0.0757  0.9350 +- 0.0550       0.0075

In [7]:
start_id = 451
end_id = 600
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df

---- Details of best experiment ----
ID: 581 ValAcc: 96.00 +- 3.74 TrnAcc: 99.00 +- 2.00 TestAcc: 93.81 +- 1.07
------------------------------------

               ValAcc            TrnAcc  regularizer
581  0.9600 +- 0.0374  0.9900 +- 0.0200       0.0750
591  0.9600 +- 0.0374  0.9900 +- 0.0200       0.1000
571  0.9450 +- 0.0522  0.9900 +- 0.0200       0.0500
531  0.9400 +- 0.0490  0.9500 +- 0.0500       0.0050
451  0.9350 +- 0.0320  1.0000 +- 0.0000       0.7500
461  0.9350 +- 0.0320  1.0000 +- 0.0000       1.0000
471  0.9350 +- 0.0320  1.0000 +- 0.0000       2.5000
481  0.9350 +- 0.0320  1.0000 +- 0.0000       5.0000
491  0.9350 +- 0.0320  1.0000 +- 0.0000       7.5000
501  0.9350 +- 0.0320  1.0000 +- 0.0000      10.0000
541  0.9350 +- 0.0502  0.9650 +- 0.0391       0.0075
551  0.9350 +- 0.0502  0.9650 +- 0.0391       0.0100
561  0.9350 +- 0.0502  0.9800 +- 0.0245       0.0250
511  0.9300 +- 0.0557  0.9550 +- 0.0522       0.0010
521  0.9300 +- 0.0557  0.9550 +- 0.0522       0.0025

# Skipalpha

In [23]:
start_id = 1
end_id = 680
n_seeds = 10
hyperparams = ["regularizer", "skip_alpha"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skipalpha_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df.head(40)

---- Details of best experiment ----
ID: 281 ValAcc: 98.50 +- 2.29 TrnAcc: 100.00 +- 0.00 TestAcc: 96.81 +- 1.26
------------------------------------

               ValAcc            TrnAcc  regularizer  skip_alpha
281  0.9850 +- 0.0229  1.0000 +- 0.0000        0.075         0.1
321  0.9850 +- 0.0229  1.0000 +- 0.0000        0.100         0.1
361  0.9850 +- 0.0229  1.0000 +- 0.0000        0.250         0.1
401  0.9850 +- 0.0229  1.0000 +- 0.0000        0.500         0.1
441  0.9850 +- 0.0229  1.0000 +- 0.0000        0.750         0.1
481  0.9850 +- 0.0229  1.0000 +- 0.0000        1.000         0.1
521  0.9850 +- 0.0229  1.0000 +- 0.0000        2.500         0.1
561  0.9850 +- 0.0229  1.0000 +- 0.0000        5.000         0.1
601  0.9850 +- 0.0229  1.0000 +- 0.0000        7.500         0.1
641  0.9850 +- 0.0229  1.0000 +- 0.0000       10.000         0.1
291  0.9650 +- 0.0450  1.0000 +- 0.0000        0.075         0.2
331  0.9650 +- 0.0450  1.0000 +- 0.0000        0.100         0.2
371  0.9650 +- 0.0450  1.0000 +- 0.0000        0.250         0.2
411  0.9650 +- 0.0450  1.0000 +- 0.0000        0.500         0.2
451  0.9650 +- 0.0450  1.0000 +- 0.0000        0.750         0.2
491  0.9650 +- 0.0450  1.0000 +- 0.0000        1.000         0.2
531  0.9650 +- 0.0450  1.0000 +- 0.0000        2.500         0.2
571  0.9650 +- 0.0450  1.0000 +- 0.0000        5.000         0.2
611  0.9650 +- 0.0450  1.0000 +- 0.0000        7.500         0.2
651  0.9650 +- 0.0450  1.0000 +- 0.0000       10.000         0.2
301  0.9600 +- 0.0300  1.0000 +- 0.0000        0.075         0.3
341  0.9600 +- 0.0300  1.0000 +- 0.0000        0.100         0.3
381  0.9500 +- 0.0447  1.0000 +- 0.0000        0.250         0.3
421  0.9500 +- 0.0447  1.0000 +- 0.0000        0.500         0.3
461  0.9500 +- 0.0447  1.0000 +- 0.0000        0.750         0.3
501  0.9500 +- 0.0447  1.0000 +- 0.0000        1.000         0.3
541  0.9500 +- 0.0447  1.0000 +- 0.0000        2.500         0.3
581  0.9500 +- 0.0447  1.0000 +- 0.0000        5.000         0.3
621  0.9500 +- 0.0447  1.0000 +- 0.0000        7.500         0.3
661  0.9500 +- 0.0447  1.0000 +- 0.0000       10.000         0.3
241  0.9450 +- 0.0472  1.0000 +- 0.0000        0.050         0.1
251  0.9350 +- 0.0776  1.0000 +- 0.0000        0.050         0.2
261  0.9350 +- 0.0743  1.0000 +- 0.0000        0.050         0.3
271  0.9300 +- 0.0714  1.0000 +- 0.0000        0.050         0.5
311  0.9300 +- 0.0678  1.0000 +- 0.0000        0.075         0.5
351  0.9250 +- 0.0642  1.0000 +- 0.0000        0.100         0.5
391  0.9100 +- 0.0800  1.0000 +- 0.0000        0.250         0.5
431  0.9100 +- 0.0800  1.0000 +- 0.0000        0.500         0.5
471  0.9100 +- 0.0800  1.0000 +- 0.0000        0.750         0.5
511  0.9100 +- 0.0800  1.0000 +- 0.0000        1.000         0.5

In [24]:
start_id = 681
end_id = 1360
n_seeds = 10
hyperparams = ["regularizer", "skip_alpha"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skipalpha_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df.head(40)

---- Details of best experiment ----
ID: 1011 ValAcc: 97.00 +- 4.00 TrnAcc: 100.00 +- 0.00 TestAcc: 96.07 +- 1.69
------------------------------------

                ValAcc            TrnAcc  regularizer  skip_alpha
1011  0.9700 +- 0.0400  1.0000 +- 0.0000        0.100         0.2
1051  0.9700 +- 0.0400  1.0000 +- 0.0000        0.250         0.2
1091  0.9700 +- 0.0400  1.0000 +- 0.0000        0.500         0.2
1131  0.9700 +- 0.0400  1.0000 +- 0.0000        0.750         0.2
1171  0.9700 +- 0.0400  1.0000 +- 0.0000        1.000         0.2
1211  0.9700 +- 0.0400  1.0000 +- 0.0000        2.500         0.2
1251  0.9700 +- 0.0400  1.0000 +- 0.0000        5.000         0.2
1291  0.9700 +- 0.0400  1.0000 +- 0.0000        7.500         0.2
1331  0.9700 +- 0.0400  1.0000 +- 0.0000       10.000         0.2
961   0.9600 +- 0.0374  0.9950 +- 0.0150        0.075         0.1
1001  0.9550 +- 0.0350  1.0000 +- 0.0000        0.100         0.1
1041  0.9550 +- 0.0350  1.0000 +- 0.0000        0.250         0.1
1081  0.9550 +- 0.0350  1.0000 +- 0.0000        0.500         0.1
1121  0.9550 +- 0.0350  1.0000 +- 0.0000        0.750         0.1
1161  0.9550 +- 0.0350  1.0000 +- 0.0000        1.000         0.1
1201  0.9550 +- 0.0350  1.0000 +- 0.0000        2.500         0.1
1241  0.9550 +- 0.0350  1.0000 +- 0.0000        5.000         0.1
1281  0.9550 +- 0.0350  1.0000 +- 0.0000        7.500         0.1
1321  0.9550 +- 0.0350  1.0000 +- 0.0000       10.000         0.1
971   0.9500 +- 0.0632  1.0000 +- 0.0000        0.075         0.2
921   0.9350 +- 0.0450  0.9950 +- 0.0150        0.050         0.1
1021  0.9350 +- 0.0594  1.0000 +- 0.0000        0.100         0.3
981   0.9300 +- 0.0781  1.0000 +- 0.0000        0.075         0.3
1061  0.9250 +- 0.0680  1.0000 +- 0.0000        0.250         0.3
1101  0.9250 +- 0.0680  1.0000 +- 0.0000        0.500         0.3
1141  0.9250 +- 0.0680  1.0000 +- 0.0000        0.750         0.3
1181  0.9250 +- 0.0680  1.0000 +- 0.0000        1.000         0.3
1221  0.9250 +- 0.0680  1.0000 +- 0.0000        2.500         0.3
1261  0.9250 +- 0.0680  1.0000 +- 0.0000        5.000         0.3
1301  0.9250 +- 0.0680  1.0000 +- 0.0000        7.500         0.3
1341  0.9250 +- 0.0680  1.0000 +- 0.0000       10.000         0.3
991   0.9150 +- 0.0743  1.0000 +- 0.0000        0.075         0.5
951   0.9100 +- 0.0800  1.0000 +- 0.0000        0.050         0.5
1031  0.9050 +- 0.0879  1.0000 +- 0.0000        0.100         0.5
931   0.9050 +- 0.0934  1.0000 +- 0.0000        0.050         0.2
1071  0.9000 +- 0.0866  1.0000 +- 0.0000        0.250         0.5
1111  0.9000 +- 0.0866  1.0000 +- 0.0000        0.500         0.5
1151  0.9000 +- 0.0866  1.0000 +- 0.0000        0.750         0.5
1191  0.9000 +- 0.0866  1.0000 +- 0.0000        1.000         0.5
1231  0.9000 +- 0.0866  1.0000 +- 0.0000        2.500         0.5

In [25]:
start_id = 1361
end_id = 2040
n_seeds = 10
hyperparams = ["regularizer", "skip_alpha"]
pred_method = "svm"
dataset = "cora_ml_binary"
collection= "l_coramlb_hyper_ntk_gcn_skipalpha_depth" #todo: rename colelction to trn_ntk_gcn
df = utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)
df.head(40)

---- Details of best experiment ----
ID: 1721 ValAcc: 96.00 +- 3.74 TrnAcc: 100.00 +- 0.00 TestAcc: 94.28 +- 1.68
------------------------------------

                ValAcc            TrnAcc  regularizer  skip_alpha
1721  0.9600 +- 0.0374  1.0000 +- 0.0000        0.250         0.1
1761  0.9600 +- 0.0374  1.0000 +- 0.0000        0.500         0.1
1801  0.9600 +- 0.0374  1.0000 +- 0.0000        0.750         0.1
1841  0.9600 +- 0.0374  1.0000 +- 0.0000        1.000         0.1
1881  0.9600 +- 0.0374  1.0000 +- 0.0000        2.500         0.1
1921  0.9600 +- 0.0374  1.0000 +- 0.0000        5.000         0.1
1961  0.9600 +- 0.0374  1.0000 +- 0.0000        7.500         0.1
2001  0.9600 +- 0.0374  1.0000 +- 0.0000       10.000         0.1
1681  0.9550 +- 0.0350  0.9900 +- 0.0200        0.100         0.1
1641  0.9450 +- 0.0472  0.9900 +- 0.0200        0.075         0.1
1731  0.9350 +- 0.0709  1.0000 +- 0.0000        0.250         0.2
1771  0.9350 +- 0.0709  1.0000 +- 0.0000        0.500         0.2
1811  0.9350 +- 0.0709  1.0000 +- 0.0000        0.750         0.2
1851  0.9350 +- 0.0709  1.0000 +- 0.0000        1.000         0.2
1891  0.9350 +- 0.0709  1.0000 +- 0.0000        2.500         0.2
1931  0.9350 +- 0.0709  1.0000 +- 0.0000        5.000         0.2
1971  0.9350 +- 0.0709  1.0000 +- 0.0000        7.500         0.2
2011  0.9350 +- 0.0709  1.0000 +- 0.0000       10.000         0.2
1601  0.9250 +- 0.0602  0.9800 +- 0.0332        0.050         0.1
1631  0.9050 +- 0.0789  1.0000 +- 0.0000        0.050         0.5
1561  0.9000 +- 0.0548  0.9800 +- 0.0332        0.025         0.1
1671  0.9000 +- 0.0894  1.0000 +- 0.0000        0.075         0.5
1741  0.9000 +- 0.0742  1.0000 +- 0.0000        0.250         0.3
1781  0.8950 +- 0.0723  1.0000 +- 0.0000        0.500         0.3
1821  0.8950 +- 0.0723  1.0000 +- 0.0000        0.750         0.3
1861  0.8950 +- 0.0723  1.0000 +- 0.0000        1.000         0.3
1901  0.8950 +- 0.0723  1.0000 +- 0.0000        2.500         0.3
1941  0.8950 +- 0.0723  1.0000 +- 0.0000        5.000         0.3
1981  0.8950 +- 0.0723  1.0000 +- 0.0000        7.500         0.3
2021  0.8950 +- 0.0723  1.0000 +- 0.0000       10.000         0.3
1711  0.8900 +- 0.0943  1.0000 +- 0.0000        0.100         0.5
1751  0.8900 +- 0.0943  1.0000 +- 0.0000        0.250         0.5
1791  0.8900 +- 0.0943  1.0000 +- 0.0000        0.500         0.5
1831  0.8900 +- 0.0943  1.0000 +- 0.0000        0.750         0.5
1871  0.8900 +- 0.0943  1.0000 +- 0.0000        1.000         0.5
1911  0.8900 +- 0.0943  1.0000 +- 0.0000        2.500         0.5
1951  0.8900 +- 0.0943  1.0000 +- 0.0000        5.000         0.5
1991  0.8900 +- 0.0943  1.0000 +- 0.0000        7.500         0.5
2031  0.8900 +- 0.0943  1.0000 +- 0.0000       10.000         0.5
1701  0.8800 +- 0.0954  1.0000 +- 0.0000        0.100         0.3