In [2]:
# Reload modules automatically
# https://ipython.readthedocs.io/en/stable/config/extensions/autoreload.html
%load_ext autoreload
%autoreload 2

In [3]:
import utils

In [7]:
start_id = 1
end_id = 130
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "pubmed"
collection= "l_pubmed_hyper_ntk_gcn" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 121 ValAcc: 79.83 +- 3.51 TrnAcc: 99.00 +- 0.82 TestAcc: 78.38 +- 1.51
------------------------------------

               ValAcc            TrnAcc  regularizer
121  0.7983 +- 0.0351  0.9900 +- 0.0082      50.0000
111  0.7758 +- 0.0334  0.9225 +- 0.0187      10.0000
101  0.7717 +- 0.0509  0.8933 +- 0.0286       5.0000
91   0.7675 +- 0.0502  0.8683 +- 0.0273       2.0000
81   0.7575 +- 0.0469  0.8617 +- 0.0289       1.0000
71   0.7042 +- 0.0364  0.8400 +- 0.0329       0.5000
1    0.6883 +- 0.0386  0.7950 +- 0.0277       0.0001
11   0.6883 +- 0.0386  0.7950 +- 0.0277       0.0005
21   0.6883 +- 0.0386  0.7950 +- 0.0277       0.0010
31   0.6883 +- 0.0386  0.7950 +- 0.0277       0.0050
41   0.6883 +- 0.0386  0.7950 +- 0.0277       0.0100
51   0.6883 +- 0.0386  0.7950 +- 0.0277       0.0500
61   0.6883 +- 0.0386  0.7950 +- 0.0277       0.1000

In [5]:
start_id = 1
end_id = 230
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora"
collection= "l_cora_n_labeled10_hyper_ntk_gcn" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 91 ValAcc: 80.64 +- 3.07 TrnAcc: 94.29 +- 1.63 TestAcc: 78.11 +- 2.25
------------------------------------

               ValAcc            TrnAcc  regularizer
91   0.8064 +- 0.0307  0.9429 +- 0.0163      0.00750
191  0.8057 +- 0.0311  0.9429 +- 0.0186      0.00800
201  0.8050 +- 0.0308  0.9443 +- 0.0171      0.00850
221  0.8050 +- 0.0293  0.9450 +- 0.0169      0.00950
101  0.8043 +- 0.0277  0.9450 +- 0.0169      0.01000
171  0.8036 +- 0.0305  0.9421 +- 0.0155      0.00650
211  0.8036 +- 0.0295  0.9450 +- 0.0169      0.00900
111  0.8029 +- 0.0317  0.9700 +- 0.0135      0.10000
181  0.8029 +- 0.0305  0.9421 +- 0.0144      0.00700
121  0.8021 +- 0.0419  0.9986 +- 0.0029      1.00000
161  0.8014 +- 0.0332  0.9400 +- 0.0140      0.00600
151  0.8000 +- 0.0360  0.9393 +- 0.0157      0.00550
131  0.7943 +- 0.0417  1.0000 +- 0.0000      5.00000
141  0.7943 +- 0.0417  1.0000 +- 0.0000     10.00000
81   0.7893 +- 0.0308  0.9336 +- 0.0150      0.00500
71   0.7821 +- 0.0335  0.9343 +- 0.0177      0.00450
51   0.7800 +- 0.0313  0.9371 +- 0.0177      0.00350
61   0.7771 +- 0.0335  0.9336 +- 0.0202      0.00400
41   0.7614 +- 0.0370  0.9271 +- 0.0255      0.00300
1    0.7371 +- 0.0353  0.9014 +- 0.0265      0.00100
11   0.7371 +- 0.0353  0.9014 +- 0.0265      0.00175
21   0.7371 +- 0.0353  0.9057 +- 0.0294      0.00200
31   0.7371 +- 0.0353  0.9164 +- 0.0279      0.00250

In [12]:
start_id = 1
end_id = 100
n_seeds = 10
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora"
collection= "l_cora_hyper_ntk_gcn" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=10)

---- Details of best experiment ----
ID: 81 ValAcc: 83.64 +- 0.63 TrnAcc: 95.82 +- 0.95 TestAcc: 82.30 +- 1.42
------------------------------------

              ValAcc            TrnAcc  regularizer
81  0.8364 +- 0.0063  0.9582 +- 0.0095      0.10000
91  0.8221 +- 0.0151  0.9954 +- 0.0051      1.00000
71  0.8218 +- 0.0124  0.9229 +- 0.0083      0.01000
51  0.8214 +- 0.0137  0.9068 +- 0.0137      0.00350
61  0.8214 +- 0.0131  0.9132 +- 0.0110      0.00500
41  0.8193 +- 0.0170  0.9029 +- 0.0156      0.00300
31  0.8157 +- 0.0180  0.9021 +- 0.0133      0.00250
21  0.8118 +- 0.0163  0.9014 +- 0.0128      0.00200
11  0.8043 +- 0.0225  0.9011 +- 0.0151      0.00175
1   0.7711 +- 0.0270  0.8679 +- 0.0382      0.00100

## MSVM

In [8]:
start_id = 1
end_id = 100
n_seeds = 5
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "cora"
collection= "l_cora_hyper_ntk_gcn" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=5)

---- Details of best experiment ----
ID: 81 ValAcc: 63.21 +- 3.72 TrnAcc: 71.71 +- 9.61 TestAcc: 55.62 +- 12.98
------------------------------------

              ValAcc            TrnAcc  regularizer
81  0.6321 +- 0.0372  0.7171 +- 0.0961      0.10000
1   0.6164 +- 0.0444  0.6786 +- 0.1206      0.00100
11  0.6164 +- 0.0444  0.6786 +- 0.1206      0.00175
21  0.6164 +- 0.0444  0.6786 +- 0.1206      0.00200
31  0.6164 +- 0.0444  0.6786 +- 0.1206      0.00250
41  0.6164 +- 0.0444  0.6786 +- 0.1206      0.00300
51  0.6164 +- 0.0444  0.6786 +- 0.1206      0.00350
61  0.6164 +- 0.0444  0.6786 +- 0.1206      0.00500
71  0.6164 +- 0.0444  0.6786 +- 0.1206      0.01000
86  0.5614 +- 0.0429  0.7279 +- 0.0795      0.10000
6   0.5607 +- 0.0379  0.7479 +- 0.0737      0.00100
16  0.5607 +- 0.0379  0.7479 +- 0.0737      0.00175
26  0.5607 +- 0.0379  0.7479 +- 0.0737      0.00200
36  0.5607 +- 0.0379  0.7479 +- 0.0737      0.00250
46  0.5607 +- 0.0379  0.7479 +- 0.0737      0.00300
56  0.5607 +- 0.0379  0.7479 +- 0.0737      0.00350
66  0.5607 +- 0.0379  0.7479 +- 0.0737      0.00500
76  0.5607 +- 0.0379  0.7479 +- 0.0737      0.01000
91  0.4614 +- 0.0744  0.5764 +- 0.1593      1.00000
96  0.4336 +- 0.0701  0.5714 +- 0.1366      1.00000

In [9]:
start_id = 1
end_id = 100
n_seeds = 5
hyperparams = ["regularizer"]
pred_method = "svm"
dataset = "pubmed"
collection= "l_pubmed_hyper_ntk_gcn" #todo: rename colelction to trn_ntk_gcn
utils.get_best_hyperparams(start_id, end_id, n_seeds, hyperparams, 
                           pred_method, dataset, collection, use_seeds=5)

---- Details of best experiment ----
ID: 1 ValAcc: 62.67 +- 3.92 TrnAcc: 72.83 +- 2.61 TestAcc: 58.08 +- 3.33
------------------------------------

              ValAcc            TrnAcc  regularizer
1   0.6267 +- 0.0392  0.7283 +- 0.0261       0.0001
11  0.6267 +- 0.0392  0.7283 +- 0.0261       0.0005
21  0.6267 +- 0.0392  0.7283 +- 0.0261       0.0010
31  0.6267 +- 0.0392  0.7283 +- 0.0261       0.0050
41  0.6267 +- 0.0392  0.7283 +- 0.0261       0.0100
51  0.6267 +- 0.0392  0.7283 +- 0.0261       0.0500
61  0.6267 +- 0.0392  0.7283 +- 0.0261       0.1000
71  0.6267 +- 0.0392  0.7283 +- 0.0261       0.5000
81  0.6267 +- 0.0392  0.7283 +- 0.0261       1.0000
91  0.6267 +- 0.0392  0.7283 +- 0.0261       2.0000
6   0.5900 +- 0.0213  0.7267 +- 0.0895       0.0001
16  0.5900 +- 0.0213  0.7267 +- 0.0895       0.0005
26  0.5900 +- 0.0213  0.7267 +- 0.0895       0.0010
36  0.5900 +- 0.0213  0.7267 +- 0.0895       0.0050
46  0.5900 +- 0.0213  0.7267 +- 0.0895       0.0100
56  0.5900 +- 0.0213  0.7267 +- 0.0895       0.0500
66  0.5900 +- 0.0213  0.7267 +- 0.0895       0.1000
76  0.5900 +- 0.0213  0.7267 +- 0.0895       0.5000
86  0.5900 +- 0.0213  0.7267 +- 0.0895       1.0000
96  0.5900 +- 0.0213  0.7267 +- 0.0895       2.0000